// ============================================================
// typing_data.js  ─  タイピング練習用の言葉データ（小1〜中3）
// ============================================================

const TYPING_DB = {
    g1: [ // 小1: 70 words
        { display: 'いぬ', romaji: 'inu' }, { display: 'ねこ', romaji: 'neko' }, { display: 'うみ', romaji: 'umi' }, { display: 'あめ', romaji: 'ame' }, { display: 'はな', romaji: 'hana' },
        { display: 'とり', romaji: 'tori' }, { display: 'くも', romaji: 'kumo' }, { display: 'あお', romaji: 'ao' }, { display: 'あか', romaji: 'aka' }, { display: 'しろ', romaji: 'siro' },
        { display: 'ゆき', romaji: 'yuki' }, { display: 'かぜ', romaji: 'kaze' }, { display: 'つき', romaji: 'tuki' }, { display: 'むし', romaji: 'musi' }, { display: 'くさ', romaji: 'kusa' },
        { display: 'き', romaji: 'ki' }, { display: 'いけ', romaji: 'ike' }, { display: 'かば', romaji: 'kaba' }, { display: 'あり', romaji: 'ari' }, { display: 'さる', romaji: 'saru' },
        { display: 'うさぎ', romaji: 'usagi' }, { display: 'わに', romaji: 'wani' }, { display: 'かめ', romaji: 'kame' }, { display: 'くま', romaji: 'kuma' }, { display: 'りす', romaji: 'risu' },
        { display: 'からす', romaji: 'karasu' }, { display: 'はと', romaji: 'hato' }, { display: 'めだか', romaji: 'medaka' }, { display: 'ふね', romaji: 'hune' }, { display: 'みち', romaji: 'miti' },
        { display: 'あさ', romaji: 'asa' }, { display: 'よる', romaji: 'yoru' }, { display: 'ひる', romaji: 'hiru' }, { display: 'つち', romaji: 'tuti' }, { display: 'いし', romaji: 'isi' },
        { display: 'はる', romaji: 'haru' }, { display: 'なつ', romaji: 'natu' }, { display: 'あき', romaji: 'aki' }, { display: 'ふゆ', romaji: 'huyu' }, { display: 'はし', romaji: 'hasi' },
        { display: 'みどりのき', romaji: 'midorinoki' }, { display: 'あかいはな', romaji: 'akaihana' }, { display: 'あおいとり', romaji: 'aoitori' }, { display: 'しろいゆき', romaji: 'siroiyuki' }, { display: 'ひろいうみ', romaji: 'hiroumi' },
        { display: 'おにぎり', romaji: 'onigiri' }, { display: 'さかな', romaji: 'sakana' }, { display: 'むしめがね', romaji: 'musimegane' }, { display: 'えのぐ', romaji: 'enogu' }, { display: 'ずこう', romaji: 'zukou' },
        { display: 'なし', romaji: 'nasi' }, { display: 'かき', romaji: 'kaki' }, { display: 'いも', romaji: 'imo' }, { display: 'たまご', romaji: 'tamago' }, { display: 'にこにこ', romaji: 'nikoniko' },
        { display: 'きらきら', romaji: 'kirakira' }, { display: 'ぴかぴか', romaji: 'pikapika' }, { display: 'わくわく', romaji: 'wakuwaku' }, { display: 'えがお', romaji: 'egao' }, { display: 'きもち', romaji: 'kimoti' },
        { display: 'おもちゃ', romaji: 'omotya' }, { display: 'えほん', romaji: 'ehon' }, { display: 'あそび', romaji: 'asobi' }, { display: 'てがみ', romaji: 'tegami' }, { display: 'ふうせん', romaji: 'huusen' },
        { display: 'たこ', romaji: 'tako' }, { display: 'こま', romaji: 'koma' }, { display: 'なわとび', romaji: 'nawatobi' }, { display: 'ともだち', romaji: 'tomodati' }, { display: 'がっこう', romaji: 'gakkou' }
    ],
    g2: [ // 小2: 70 words
        { display: 'りんご', romaji: 'ringo' }, { display: 'みかん', romaji: 'mikan' }, { display: 'えんぴつ', romaji: 'enpitu' }, { display: 'かぞく', romaji: 'kazoku' }, { display: 'きっぷ', romaji: 'kippu' },
        { display: 'がっこう', romaji: 'gakkou' }, { display: 'あそぶ', romaji: 'asobu' }, { display: 'うたう', romaji: 'utau' }, { display: 'ごはん', romaji: 'gohan' }, { display: 'おちゃ', romaji: 'otya' },
        { display: 'おかし', romaji: 'okasi' }, { display: 'くるま', romaji: 'kuruma' }, { display: 'きつね', romaji: 'kitune' }, { display: 'うさぎ', romaji: 'usagi' }, { display: 'りゅう', romaji: 'ryuu' },
        { display: 'きりん', romaji: 'kirin' }, { display: 'じかん', romaji: 'jikan' }, { display: 'とけい', romaji: 'tokei' }, { display: 'えほん', romaji: 'ehon' }, { display: 'つみき' , romaji: 'tumiki' },
        { display: 'バナナ', romaji: 'banana' }, { display: 'スイカ', romaji: 'suika' }, { display: 'メロン', romaji: 'meron' }, { display: 'トマト', romaji: 'tomato' }, { display: 'ナス', romaji: 'nasu' },
        { display: 'キャベツ', romaji: 'kyabetu' }, { display: 'レタス', romaji: 'retasu' }, { display: 'にんじん', romaji: 'ninjin' }, { display: 'きゅうり', romaji: 'kyuuri' }, { display: 'たまねぎ', romaji: 'tamanegi' },
        { display: 'つくえ', romaji: 'tukue' }, { display: 'いす', romaji: 'isu' }, { display: 'かばん', romaji: 'kaban' }, { display: 'ぼうし', romaji: 'bousi' }, { display: 'くつ下', romaji: 'kutushita' },
        { display: 'おんがく', romaji: 'ongaku' }, { display: 'たいいく', romaji: 'taiiku' }, { display: 'ずこう', romaji: 'zukou' }, { display: 'さんすう', romaji: 'sansuu' }, { display: 'こくご', romaji: 'kokugo' },
        { display: 'こうえん', romaji: 'kouen' }, { display: 'でんしゃ', romaji: 'densya' }, { display: 'ばす', romaji: 'basu' }, { display: 'ひこうき', romaji: 'hikouki' }, { display: 'じてんしゃ', romaji: 'jitensya' },
        { display: 'おじいさん', romaji: 'ojiisan' }, { display: 'おばあさん', romaji: 'obaasan' }, { display: 'おとうさん', romaji: 'otousan' }, { display: 'おかあさん', romaji: 'okaasan' }, { display: 'こども', romaji: 'kodomo' },
        { display: 'おべんとう', romaji: 'obentou' }, { display: 'ぎゅうにゅう', romaji: 'gyuunyuu' }, { display: 'パンケーキ', romaji: 'panke-ki' }, { display: 'ドーナツ', romaji: 'do-natu' }, { display: 'ソフトクリーム', romaji: 'sofutokuri-mu' },
        { display: 'どうぶつ', romaji: 'doubutu' }, { display: 'こうえんであそぶ', romaji: 'kouendeasobu' }, { display: 'あしたははれ', romaji: 'asitahahare' }, { display: 'ほんをよむ', romaji: 'honnwoyomu' }, { display: 'えをかく', romaji: 'ewokaku' },
        { display: 'ひっ算', romaji: 'hissan' }, { display: 'くり上がり', romaji: 'kuriagari' }, { display: 'くり下がり', romaji: 'kurisagari' }, { display: 'ものさし', romaji: 'monosasi' }, { display: 'ながさ', romaji: 'nagasa' },
        { display: 'かさ', romaji: 'kasa' }, { display: 'じかん', romaji: 'jikan' }, { display: 'まい日', romaji: 'mainiti' }, { display: 'にっき', romaji: 'nikki' }, { display: 'しゅくだい', romaji: 'syukudai' }
    ],
    g3: [ // 小3: 70 words
        { display: 'がっこう', romaji: 'gakkou' }, { display: 'せんせい', romaji: 'sensei' }, { display: 'じてんしゃ', romaji: 'jitensya' }, { display: 'としょかん', romaji: 'tosyokan' }, { display: 'びょういん', romaji: 'byouin' },
        { display: 'ともだち', romaji: 'tomodati' }, { display: 'おんがく', romaji: 'ongaku' }, { display: 'がいこく', romaji: 'gaikoku' }, { display: 'ぶんぼうぐ', romaji: 'bunbougu' }, { display: 'たいよう', romaji: 'taiyou' },
        { display: 'ちきゅう', romaji: 'tikyuu' }, { display: 'どうぶつえん', romaji: 'doubutuen' }, { display: 'すいえい', romaji: 'suiei' }, { display: 'やきゅう', romaji: 'yakyuu' }, { display: 'サッカー', romaji: 'sakka-' },
        { display: 'ピアノ', romaji: 'piano' }, { display: 'カメラ', romaji: 'kamera' }, { display: 'テレビ', romaji: 'terebi' }, { display: 'パソコン', romaji: 'pasokon' }, { display: 'スマート', romaji: 'suma-to' },
        { display: 'かいもの', romaji: 'kaimono' }, { display: 'おべんとう', romaji: 'obentou' }, { display: 'おまつり', romaji: 'omaturi' }, { display: 'えんそく', romaji: 'ensoku' }, { display: 'うんどうかい', romaji: 'undoukai' },
        { display: 'しゅくだい', romaji: 'syukudai' }, { display: 'てすと', romaji: 'tesuto' }, { display: 'しょじどう', romaji: 'syojidou' }, { display: 'りか', romaji: 'rika' }, { display: 'しゃかい', romaji: 'syakai' },
        { display: 'こうじょう', romaji: 'koujou' }, { display: 'スーパー', romaji: 'su-pa-' }, { display: 'コンビニ', romaji: 'konbini' }, { display: 'パンやさん', romaji: 'panyasan' }, { display: 'はなやさん', romaji: 'hanayasan' },
        { display: 'ほしぞら', romaji: 'hosizora' }, { display: 'ことわざ', romaji: 'kotowaza' }, { display: 'おまわりさん', romaji: 'omawarisan' }, { display: 'しょうぼうし', romaji: 'syoubousi' }, { display: 'かんごし', romaji: 'kangosi' },
        { display: 'あさごはん', romaji: 'asagohan' }, { display: 'ばんごはん', romaji: 'bangohan' }, { display: 'おひるごはん', romaji: 'ohirugohan' }, { display: 'なつやすみ', romaji: 'natuyasumi' }, { display: 'ふゆやすみ', romaji: 'huyuyasumi' },
        { display: 'はるやすみ', romaji: 'haruyasumi' }, { display: 'あめふり', romaji: 'amehuri' }, { display: 'かみなり', romaji: 'kaminari' }, { display: 'にじ', romaji: 'niji' }, { display: 'あじさい', romaji: 'ajisai' },
        { display: 'モンシロチョウ', romaji: 'monsirotyou' }, { display: 'ひまわりのタネ', romaji: 'himawarinotane' }, { display: 'ホウセンカ', romaji: 'housenka' }, { display: 'じしゃく', romaji: 'jisyaku' }, { display: '豆電球', romaji: 'mamedenkyuu' },
        { display: '乾電池', romaji: 'kandenti' }, { display: '方位磁石', romaji: 'houwijisyaku' }, { display: '気温', romaji: 'kiwon' }, { display: '温度計', romaji: 'ondokei' }, { display: 'はかり', romaji: 'hakari' },
        { display: 'あまりのあるわり算', romaji: 'amari-no-aru-warizan' }, { display: '万（まん）', romaji: 'mann' }, { display: '小数（しょうすう）', romaji: 'syousuu' }, { display: '分数（ぶんすう）', romaji: 'bunsuu' }, { display: '円（えん）', romaji: 'enn' },
        { display: '球（たま）', romaji: 'tama' }, { display: 'コンパス', romaji: 'konpasu' }, { display: '重さ（おもさ）', romaji: 'omosa' }, { display: '二等辺三角形', romaji: 'nitouhensankakukei' }, { display: '正三角形', romaji: 'seisankakukei' }
    ],
    g4: [ // 小4: 70 words
        { display: 'プログラミング', romaji: 'puroguramingu' }, { display: 'インターネット', romaji: 'inta-netto' }, { display: 'けいさつしょ', romaji: 'keisatusyo' }, { display: 'しょうぼうしょ', romaji: 'syoubousyo' }, { display: 'ぜんこくたいかい', romaji: 'zenkokutaikai' },
        { display: 'しぜんかんきょう', romaji: 'sizenkankyou' }, { display: 'ぼうさいくんれん', romaji: 'bousaikunren' }, { display: 'がいこくご', romaji: 'gaikokugo' }, { display: 'じょうほう', romaji: 'jouhou' }, { display: 'てんきよほう', romaji: 'tenkiyohou' },
        { display: 'きょうりゅう', romaji: 'kyouryuu' }, { display: 'ほきょく', romaji: 'hokkyoku' }, { display: 'なんきょく', romaji: 'nankyoku' }, { display: 'すいぞくかん', romaji: 'suizokukan' }, { display: 'はくぶつかん', romaji: 'hakubutukan' },
        { display: 'びじゅつかん', romaji: 'bijutukan' }, { display: 'かせんじき', romaji: 'kasenjiki' }, { display: 'てんもんざい', romaji: 'tenmonndai' }, { display: 'うちゅうせん', romaji: 'utyuusen' }, { display: 'わくせい', romaji: 'wakusei' },
        { display: 'えいきょう', romaji: 'eikyou' }, { display: 'かんしゃ', romaji: 'kansya' }, { display: 'きじゅん', romaji: 'kijun' }, { display: 'こうけん', romaji: 'kouken' }, { display: 'しゃかい', romaji: 'syakai' },
        { display: 'せいこう', romaji: 'seikou' }, { display: 'そうぞう', romaji: 'souzou' }, { display: 'たいおう', romaji: 'taiou' }, { display: 'てんとう', romaji: 'tentou' }, { display: 'はってん', romaji: 'hatten' },
        { display: 'ひかく', romaji: 'hikaku' }, { display: 'ほうこく', romaji: 'houkoku' }, { display: 'りかい', romaji: 'rikai' }, { display: 'れんらく', romaji: 'renraku' }, { display: 'ぎもん', romaji: 'gimon' },
        { display: 'けいけん', romaji: 'keiken' }, { display: 'しっぱい', romaji: 'sippai' }, { display: 'じゅんび', romaji: 'junbi' }, { display: 'せいり', romaji: 'seiri' }, { display: 'ちょうさ', romaji: 'tyousa' },
        { display: 'ぶんせき', romaji: 'bunseki' }, { display: 'かいけつ', romaji: 'kaiketu' }, { display: 'ほうほう', romaji: 'houhou' }, { display: 'けっか', romaji: 'kekka' }, { display: 'もくてき', romaji: 'mokuteki' },
        { display: 'げんいん', romaji: 'genin' }, { display: 'りゆう', romaji: 'riyuu' }, { display: 'いけん', romaji: 'iken' }, { display: 'かんそう', romaji: 'kansou' }, { display: 'きろく', romaji: 'kiroku' },
        { display: '都道府県', romaji: 'todoufuken' }, { display: '県庁所在地', romaji: 'kentyousyozaiti' }, { display: '廃棄物処理', romaji: 'haikibuturyori' }, { display: '浄水場', romaji: 'jousuijyou' }, { display: '伝統工芸', romaji: 'dentoukougei' },
        { display: '星座', romaji: 'seiza' }, { display: '月の動き', romaji: 'tukinougoki' }, { display: '関節', romaji: 'kansetu' }, { display: '筋肉', romaji: 'kinniku' }, { display: '電気の通り道', romaji: 'denkinotoorimiti' },
        { display: '兆（ちょう）', romaji: 'tyou' }, { display: '概数（がいすう）', romaji: 'gaisuu' }, { display: '平行四辺形', romaji: 'heikousihenkei' }, { display: '台形（だいけい）', romaji: 'daikei' }, { display: 'ひし形', romaji: 'hisigata' },
        { display: '立方体', romaji: 'rippoutai' }, { display: '直方体', romaji: 'tyokuhoutai' }, { display: '折れ線グラフ', romaji: 'oresengurafu' }, { display: '面積', romaji: 'menseki' }, { display: '垂直と平行', romaji: 'suitukutoheikou' }
    ],
    g5: [ // 小5: 70 words
        { display: 'かんきょうもんだい', romaji: 'kankyoumondai' }, { display: 'ちきゅうおんだんか', romaji: 'tikyuuondanka' }, { display: 'しょくりょうきき', romaji: 'syokuryoukiki' }, { display: 'にさんかたんそ', romaji: 'nisankatanso' }, { display: 'えいせいほうそう', romaji: 'eiseihousou' },
        { display: 'さいせいかのう', romaji: 'saiseikanou' }, { display: 'エネルギー', romaji: 'enerugi-' }, { display: 'ボランティア', romaji: 'borantiia' }, { display: 'リサイクル', romaji: 'risaikuru' }, { display: 'ハイブリッド', romaji: 'haiburiddo' },
        { display: 'コミュニケーション', romaji: 'komyunike-syon' }, { display: 'デジタルカメラ', romaji: 'dejitarukamera' }, { display: 'スマートフォン', romaji: 'suma-tofon' }, { display: 'タブレット', romaji: 'taburetto' }, { display: 'クラウド', romaji: 'kuraudo' },
        { display: 'セキュリティ', romaji: 'sekyuriti' }, { display: 'パスワード', romaji: 'pasuwa-do' }, { display: 'ソフトウェア', romaji: 'sofutowea' }, { display: 'ハードウェア', romaji: 'ha-dowea' }, { display: 'データベース', romaji: 'de-tabe-su' },
        { display: '人工知能', romaji: 'jinkoutinou' }, { display: 'ロボット', romaji: 'robotto' }, { display: 'ドローン', romaji: 'doro-n' }, { display: 'バーチャル', romaji: 'ba-tyaru' }, { display: 'リアリティ', romaji: 'riaritthi' },
        { display: 'テクノロジー', romaji: 'tekunoroji-' }, { display: 'ネットワーク', romaji: 'nettowa-ku' }, { display: 'オンライン', romaji: 'onrain' }, { display: 'ダウンロード', romaji: 'daunro-do' }, { display: 'アップロード', romaji: 'appuro-do' },
        { display: 'ブラウザ', romaji: 'burauza' }, { display: 'メール', romaji: 'me-ru' }, { display: 'チャット', romaji: 'tyatto' }, { display: 'ビデオつうわ', romaji: 'bideotuwa' }, { display: 'ストリーミング', romaji: 'sutori-mingu' },
        { display: 'アニメーション', romaji: 'anime-syon' }, { display: 'グラフィック', romaji: 'gurafikku' }, { display: 'デザイン', romaji: 'dezain' }, { display: 'クリエイティブ', romaji: 'kurieitibu' }, { display: 'プレゼン', romaji: 'purezen' },
        { display: 'ディスカッション', romaji: 'disukassyon' }, { display: 'プロジェクト', romaji: 'purojekuto' }, { display: 'リーダーシップ', romaji: 'ri-da-sippu' }, { display: 'チームワーク', romaji: 'ti-muwa-ku' }, { display: 'コラボレーション', romaji: 'korabore-syon' },
        { display: 'イノベーション', romaji: 'inobe-syon' }, { display: 'チャレンジ', romaji: 'tyarenji' }, { display: 'アクション', romaji: 'akusyon' }, { display: 'ビジョン', romaji: 'bijon' }, { display: 'ゴール', romaji: 'go-ru' },
        { display: '日本の産業', romaji: 'nihonnosangyou' }, { display: '日本の水産業', romaji: 'nihonnosuisangyou' }, { display: '日本の農業', romaji: 'nihonnounougyou' }, { display: '自動車工場', romaji: 'jidousyakoujou' }, { display: '情報産業', romaji: 'jouhousangyou' },
        { display: '発芽', romaji: 'hatuga' }, { display: '顕微鏡', romaji: 'kenbikyou' }, { display: '天気の変化', romaji: 'tenkinohenka' }, { display: '台風の動き', romaji: 'taifuunougoki' }, { display: '流水の働き', romaji: 'ryuusyuinonataraki' },
        { display: '割合（わりあい）', romaji: 'wariai' }, { display: '円グラフ', romaji: 'engurafu' }, { display: '平均', romaji: 'heikunn' }, { display: '単位量あたりの大きさ', romaji: 'tanniryou-atari' }, { display: '体積（たいせき）', romaji: 'taiseki' },
        { display: '倍数（ばいすう）', romaji: 'baisuu' }, { display: '公約数（こうやくすう）', romaji: 'kouyakusuu' }, { display: '通分（つうぶん）', romaji: 'tuubunn' }, { display: '速さ（はやさ）', romaji: 'hayasa' }, { display: '比（ひ）', romaji: 'hi' }
    ],
    g6: [ // 小6: 70 words
        { display: 'こくさいれんごう', romaji: 'kokusairengou' }, { display: 'オリンピック', romaji: 'orinpikku' }, { display: 'じょうほうしゃかい', romaji: 'jouhousyakai' }, { display: 'せかいいうさん', romaji: 'sekaiisan' }, { display: 'じんけんそんちょう', romaji: 'jinkensontyou' },
        { display: 'けんりょくぶんりつ', romaji: 'kenryokubunritu' }, { display: 'さいばんしょ', romaji: 'saibansyo' }, { display: 'こっかいぎしどう', romaji: 'kokkaigisidou' }, { display: 'せんきょけん', romaji: 'senkyoken' }, { display: 'に日本国憲法', romaji: 'nihonkokukenpou' },
        { display: 'へいわしゅぎ', romaji: 'heiwasyugi' }, { display: 'こくみんしゅけん', romaji: 'kokuminsyuken' }, { display: '基本的人権', romaji: 'kihontekijinken' }, { display: 'さんせいけん', romaji: 'sanseiken' }, { display: 'ろうどうけん', romaji: 'roudouken' },
        { display: 'しゃかいけん', romaji: 'syakaiken' }, { display: 'じゆうけん', romaji: 'jiyuuken' }, { display: 'じょうほうこうかい', romaji: 'jouhoukoukai' }, { display: 'ちほうじち', romaji: 'tihoujiti' }, { display: 'ざいせい', romaji: 'zaisei' },
        { display: 'しゃかいほしょう', romaji: 'syakaihosyou' }, { display: 'ねんきん', romaji: 'nenkin' }, { display: 'ほけん', romaji: 'hoken' }, { display: 'ぜいきん', romaji: 'zeikin' }, { display: 'よさん', romaji: 'yosan' },
        { display: 'けいざい', romaji: 'keizai' }, { display: 'ぼうえき', romaji: 'boueki' }, { display: 'ゆしゅつ', romaji: 'yusyutu' }, { display: 'ゆにゅう', romaji: 'yunyuu' }, { display: 'しげん', romaji: 'sigen' },
        { display: 'エネルギー', romaji: 'enerugi-' }, { display: 'かんきょうほご', romaji: 'kankyouhogo' }, { display: 'へいわいじ', romaji: 'heiwaiji' }, { display: 'こくさいきょうりょく', romaji: 'kokusaikyouryoku' }, { display: 'NGO', romaji: 'ngo' },
        { display: 'ユニセフ', romaji: 'yunisefu' }, { display: 'ユネスコ', romaji: 'yunesuko' }, { display: 'WTO', romaji: 'wto' }, { display: 'APEC', romaji: 'apec' }, { display: 'ASEAN', romaji: 'asean' },
        { display: 'EU', romaji: 'eu' }, { display: 'グローバル', romaji: 'guro-baru' }, { display: '多様性', romaji: 'tayousei' }, { display: '持続可能', romaji: 'jizokukanou' }, { display: 'SDGs', romaji: 'sdgs' },
        { display: 'カーボンニュートラル', romaji: 'ka-bonnyu-toraru' }, { display: 'デジタルトランスフォーメーション', romaji: 'dejitarutoransufyo-me-syon' }, { display: 'AI', romaji: 'ai' }, { display: 'ビッグデータ', romaji: 'biggude-ta' }, { display: 'IoT', romaji: 'iot' },
        { display: '修学旅行', romaji: 'syuugakuryokou' }, { display: '卒業記念', romaji: 'sotugyoukinen' }, { display: '中学校生活', romaji: 'tyuugakkouseikatu' }, { display: '歴史人物', romaji: 'rekisijinbutu' }, { display: '縄文時代', romaji: 'joumonjidai' },
        { display: '光合成', romaji: 'kougousei' }, { display: '水溶液', romaji: 'suiyoueki' }, { display: '心臓の働き', romaji: 'sinzounonataraki' }, { display: '食物連鎖', romaji: 'syokumuturensa' }, { display: '電気の利用', romaji: 'denkinoriyou' },
        { display: '文字と式', romaji: 'mojitosiki' }, { display: '対称な図形', romaji: 'taisyounazukkei' }, { display: '比例と反比例', romaji: 'hireitohanpirei' }, { display: '縮図・拡大図', romaji: 'syukuzu-kakudaizu' }, { display: '角柱と円柱', romaji: 'kakutyuutoentyuu' },
        { display: '資料の整理', romaji: 'siryou-no-seiri' }, { display: '組み合わせ', romaji: 'kumiawase' }, { display: '量と単位', romaji: 'ryoutotanni' }, { display: 'メートル法', romaji: 'me-toruhou' }, { display: '比例のグラフ', romaji: 'hireinogurafu' }
    ],
    m1: [ // 中1: 70 words
        { display: '方程式', romaji: 'houteisiki' }, { display: 'アルゴリズム', romaji: 'arugorizumu' }, { display: '人工知能', romaji: 'jinkoutinou' }, { display: '部活動', romaji: 'bukatudou' }, { display: '定期テスト', romaji: 'teikitesuto' },
        { display: '正負の数', romaji: 'seifunosuu' }, { display: '文字と式', romaji: 'mojitosiki' }, { display: '比例と反比例', romaji: 'hireitohanpirei' }, { display: '平面図形', romaji: 'heimenmukei' }, { display: '空間図形', romaji: 'kuukanmukei' },
        { display: '光の反射', romaji: 'hikarinnohansya' }, { display: '音の性質', romaji: 'otonoseisitu' }, { display: '力と圧力', romaji: 'tikara-toaturyoku' }, { display: '植物の分類', romaji: 'syokubutunobunrui' }, { display: '大地の変化', romaji: 'daithinohenka' },
        { display: '世界の地域', romaji: 'sekainotiiki' }, { display: '日本の地域', romaji: 'nihonnotiiki' }, { display: '古代国家', romaji: 'kodaikokka' }, { display: '武家社会', romaji: 'bukesyaki' }, { display: '産業の発達', romaji: 'sangyounohattatu' },
        { display: '抽象的', romaji: 'tyuusyuuteki' }, { display: '具体図', romaji: 'gutizu' }, { display: '矛盾', romaji: 'mujun' }, { display: '論理的', romaji: 'ronriteki' }, { display: '客観的', romaji: 'kyakkanteki' },
        { display: '主観的', romaji: 'syukkanteki' }, { display: '普遍的', romaji: 'fuhenteki' }, { display: '特殊性', romaji: 'tokusyuusei' }, { display: '概念', romaji: 'gainen' }, { display: '本質', romaji: 'honsitu' },
        { display: '定義', romaji: 'teigi' }, { display: '前提', romaji: 'zentei' }, { display: '結論', romaji: 'keturon' }, { display: '推論', romaji: 'suiron' }, { display: '検証', romaji: 'kensyou' },
        { display: '仮説', romaji: 'kasetu' }, { display: '分析', romaji: 'bunseki' }, { display: '統合', romaji: 'tougou' }, { display: '展開', romaji: 'tenkai' }, { display: '要約', romaji: 'youyaku' },
        { display: '主題', romaji: 'syudai' }, { display: '文脈', romaji: 'bunmyaku' }, { display: '表現', romaji: 'hyougen' }, { display: '描写', romaji: 'byousya' }, { display: '視点', romaji: 'siten' },
        { display: '構造', romaji: 'kouzou' }, { display: '機能', romaji: 'kinou' }, { display: '要素', romaji: 'youso' }, { display: '関係', romaji: 'kankei' }, { display: '対立', romaji: 'tairitu' },
        { display: '絶対値', romaji: 'zettaiti' }, { display: '自然数', romaji: 'sizennsuu' }, { display: '項（こう）', romaji: 'kou' }, { display: '係数', romaji: 'keisuu' }, { display: '等式と不等式', romaji: 'tousikitofutousiki' },
        { display: '垂直二等分線', romaji: 'suitukunitoubunsen' }, { display: '角の二等分線', romaji: 'kadononitoubunsen' }, { display: 'おうぎ形', romaji: 'ougigata' }, { display: '投影図', romaji: 'toueizu' }, { display: '表面積', romaji: 'hyoumenseki' },
        { display: '密度の計算', romaji: 'mitudonokeisann' }, { display: '溶解度曲線', romaji: 'youkaidokyokusen' }, { display: '蒸留（じょうりゅう）', romaji: 'jyoungyuu' }, { display: '化石の観察', romaji: 'kasekino-kansatu' }, { display: '堆積岩', romaji: 'taisekigan' },
        { display: 'マグマと火山', romaji: 'magumatokazan' }, { display: '地震の揺れ', romaji: 'jisinnnoyure' }, { display: '緯度と経度', romaji: 'idotokeido' }, { display: '時差の計算', romaji: 'jisannokeisann' }, { display: '領域の区分', romaji: 'ryouikinokubunn' }
    ],
    m2: [ // 中2: 70 words
        { display: '確率と統計', romaji: 'kakuritutotoukei' }, { display: '産業革命', romaji: 'sangyoukakumei' }, { display: '職場体験', romaji: 'syokubataiken' }, { display: '酸とアルカリ', romaji: 'santoarukari' }, { display: '連立方程式', romaji: 'renrituhouteisiki' },
        { display: '一次関数', romaji: 'itijikansuu' }, { display: '図形の性質', romaji: 'zukkeinoseisitu' }, { display: '三角形と四角形', romaji: 'sankakukeitosikakukei' }, { display: '化学変化', romaji: 'kagakuhenka' }, { display: '原子と分子', romaji: 'gensitobunsi' },
        { display: '電気の世界', romaji: 'denkinosekai' }, { display: '動物の生活', romaji: 'doubutunoseikatu' }, { display: '気象の観測', romaji: 'kisyounokansoku' }, { display: '近世の日本', romaji: 'kinseinonihon' }, { display: '近代の日本', romaji: 'kindainonihon' },
        { display: '欧米の進出', romaji: 'oubeinosinsyutu' }, { display: '地理的技能', romaji: 'tiritekkiginnou' }, { display: '人口と都市', romaji: 'jinkoutotosi' }, { display: '資源とエネルギー', romaji: 'sigentoenerugi-' }, { display: '環境の変化', romaji: 'kankyounohenka' },
        { display: '社会主義', romaji: 'syakaishugi' }, { display: '民主主義', romaji: 'minshushugi' }, { display: '資本主義', romaji: 'shihonshugi' }, { display: '帝国主義', romaji: 'teikokushugi' }, { display: 'ナショナリズム', romaji: 'nasyonarizumu' },
        { display: '立憲制', romaji: 'rikkensei' }, { display: '人権宣言', romaji: 'jinkensengen' }, { display: '独立教育', romaji: 'dokuritukyouiku' }, { display: '近代国家', romaji: 'kindaikokka' }, { display: '国際交流', romaji: 'kokusaikouryuu' },
        { display: '異文化理解', romaji: 'ibunkarikai' }, { display: '多文化共生', romaji: 'tabuinnkakkyousei' }, { display: '平和活動', romaji: 'heiwakandou' }, { display: '人道支援', romaji: 'jindousien' }, { display: '経済格差', romaji: 'keizaikakusa' },
        { display: '貧困問題', romaji: 'hinkonmondai' }, { display: '少子高齢化', romaji: 'syoushikoureika' }, { display: '地域活性化', romaji: 'tiikikasseika' }, { display: '都市計画', romaji: 'tosikeikaku' }, { display: '防災対策', romaji: 'bousaitaisaku' },
        { display: '情報倫理', romaji: 'jouhourinri' }, { display: 'プライバシー', romaji: 'puraibashi-' }, { display: '著作権', romaji: 'tyosakuken' }, { display: 'メディアリテラシー', romaji: 'mediariterashi-' }, { display: 'コミュニケーション能力', romaji: 'komyunike-syonnounyoku' },
        { display: 'リーダーシップ', romaji: 'ri-da-shippu' }, { display: 'プレゼンテーション', romaji: 'purezente-syon' }, { display: 'クリティカルシンキング', romaji: 'kuritikarusinkingu' }, { display: '問題解決能力', romaji: 'mondaikaiketunounyoku' }, { display: '自己肯定感', romaji: 'jikokouteikan' },
        { display: '単項式と多項式', romaji: 'tankousikitotakousiki' }, { display: '等式の変形', romaji: 'tousikinohenkei' }, { display: '対頂角', romaji: 'taityoukakku' }, { display: '内角と外角', romaji: 'naikakutogaikaku' }, { display: '平行線と角', romaji: 'heikousentokaku' },
        { display: '合同条件', romaji: 'goudoujouken' }, { display: '箱ひげ図', romaji: 'hakohigeyu' }, { display: '四分位数', romaji: 'sibunisuu' }, { display: '酸化と還元', romaji: 'sannkatokkanngenn' }, { display: '質量保存の法則', romaji: 'situreihouzon' },
        { display: '直並列回路', romaji: 'tyokunnheiretukairo' }, { display: '電圧の法則', romaji: 'dennatu-no-housoku' }, { display: '消化と吸収', romaji: 'syokatokyuusyuu' }, { display: '呼吸の仕組み', romaji: 'kokyuunosikumi' }, { display: '反射の速さ', romaji: 'hansyanohayasa' },
        { display: '日本の気候', romaji: 'nihonno-kikou' }, { display: '開国と近代化', romaji: 'kaikokutokindaika' }, { display: '明治維新', romaji: 'meiji-issin' }, { display: '自由民権運動', romaji: 'jiyuuminken-undou' }, { display: '日清・日露戦争', romaji: 'nissin-nituro' }
    ],
    m3: [ // 中3: 70 words
        { display: '因数分解', romaji: 'insuubunkai' }, { display: '二次方程式', romaji: 'nijihouteisiki' }, { display: '相似な図形', romaji: 'soujinazukkei' }, { display: '三平方の定理', romaji: 'sanpeihounoteiri' }, { display: '円周角の定理', romaji: 'ensyuukakunoteiri' },
        { display: '標本調査', romaji: 'hyouhontyousa' }, { display: '関数 y=ax^2', romaji: 'kansuuyax2' }, { display: '展開の公式', romaji: 'tenkainokousiki' }, { display: '電解質と非電解質', romaji: 'denkaisitutohidenkaisitu' }, { display: '原子の構造', romaji: 'gensinokouzou' },
        { display: 'イオンのなり立ち', romaji: 'ionnonaritati' }, { display: '酸・アルカリとイオン', romaji: 'santoarukarittoion' }, { display: '物体の運動', romaji: 'buttainoundou' }, { display: '仕事とエネルギー', romaji: 'sigotoenerugi-' }, { display: 'エネルギーの変換', romaji: 'eneruginohenkan' },
        { display: '生殖と遺伝', romaji: 'seisyokutoiden' }, { display: '天体の動き', romaji: 'tentainougoki' }, { display: '自然と人間', romaji: 'sizentoningen' }, { display: '現代の民主政治', romaji: 'gendainominsuseiji' }, { display: '日本国憲法', romaji: 'nihonkokukenpou' },
        { display: '基本的人権の尊重', romaji: 'kihontekijinkennsonntyou' }, { display: '国会・内閣・裁判所', romaji: 'kokkainaikakusaibansyo' }, { display: '地方自治', romaji: 'tihoujiti' }, { display: '消費生活', romaji: 'syouhiseikatu' }, { display: '市場経済', romaji: 'sitijyokeizai' },
        { display: '金融と景気', romaji: 'kinyuutokeiki' }, { display: '政府の役割', romaji: 'seifunoyakuwari' }, { display: '国際社会の課題', romaji: 'kokusaisyakaikadai' }, { display: '地球環境問題', romaji: 'tikyuukankyou' }, { display: '平和と国際協力', romaji: 'heiwatokokusai' },
        { display: '効率と公正', romaji: 'kouritutokousei' }, { display: '多文化共生社会', romaji: 'tabuinkakyousei' }, { display: '社会保障制度', romaji: 'syakaihosyouseido' }, { display: '労働の権利', romaji: 'roudounokenri' }, { display: '起業家精神', romaji: 'kigyoukaseisin' },
        { display: 'グローバル化', romaji: 'guro-baruka' }, { display: '持続可能', romaji: 'jizokukanou' }, { display: '意思決定', romaji: 'isikettei' }, { display: '自己研鑽', romaji: 'jikokensann' }, { display: '相互理解', romaji: 'sougorikai' },
        { display: '論理思考', romaji: 'ronrisikou' }, { display: '情報活用能力', romaji: 'jouhoukatuyounyoku' }, { display: '批判的分析', romaji: 'hihantekibunseki' }, { display: '多様な価値観', romaji: 'tayounakatihan' }, { display: '主体的な学び', romaji: 'syutaitekinamanabi' },
        { display: '平方根', romaji: 'heihoukon' }, { display: '無理数', romaji: 'murisuu' }, { display: '二次関数のグラフ', romaji: 'nijikansuunogurafu' }, { display: '線分比と平行線', romaji: 'senbunnhitoheikou' }, { display: '面積比と体積比', romaji: 'mensekinitoiseki' },
        { display: 'ピタゴラスの定理', romaji: 'pitagorasu-no-teiri' }, { display: '標本平均', romaji: 'hyouhouheikkun' }, { display: '母集団', romaji: 'bosyuudan' }, { display: '中和反応', romaji: 'tyuuwahanmou' }, { display: '電池の仕組み', romaji: 'dentinosikumi' },
        { display: '速さと運動', romaji: 'hayasatoundou' }, { display: '力の分解', romaji: 'tikaranobunkai' }, { display: '細胞分裂', romaji: 'saiboubinnretu' }, { display: '優性の法則', romaji: 'yuusei-no-housoku' }, { display: '太陽系と銀河系', romaji: 'taiyoukeitogingakei' },
        { display: '公戦と自転', romaji: 'kousentoziten' }, { display: '三権分立', romaji: 'sankenbunritu' }, { display: '平等権', romaji: 'byoudouken' }, { display: '自由権', romaji: 'jiyuuken' }, { display: '社会権', romaji: 'syakaiken' }
    ]
};
